[package]
entrypoint = "run"

[dependencies]
"php/php" = "=8.3.402"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-t", "/app", "-S", "localhost:8080"]

[[command]]
name = "install"
module = "php/php:php"
runner = "wasi"
[command.annotations.wasi]
main-args = ["-d", "opcache.enable=0", "-f", "/app/wasmer/install.php"]
